version: "3"

services:
  node:
    image: node:18.0.0-alpine
    user: node
    working_dir: /home/node
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
      - 9000:9000
    volumes:
      - .:/home/node
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    env_file: .env
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: ${DB_USER}
      PMA_PASSWORD: ${DB_PASSWORD}
    ports:
      - 8080:80